-- MySQL Script generated by MySQL Workbench
-- Вс. 13 марта 2016 17:19:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema WarOfViruses
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `WarOfViruses` ;

-- -----------------------------------------------------
-- Schema WarOfViruses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WarOfViruses` DEFAULT CHARACTER SET utf8 ;
USE `WarOfViruses` ;

-- -----------------------------------------------------
-- Table `WarOfViruses`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WarOfViruses`.`User` ;

CREATE TABLE IF NOT EXISTS `WarOfViruses`.`User` (
  `id` BIGINT NOT NULL,
  `googleToken` VARCHAR(255) NOT NULL,
  `nicknameStr` VARCHAR(45) NOT NULL,
  `nicknameId` INT UNSIGNED NOT NULL,
  `colorCross` INT UNSIGNED NOT NULL,
  `colorZero` INT UNSIGNED NOT NULL,
  `invitationTarget` BIGINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `googleToken_UNIQUE` (`googleToken` ASC),
  INDEX `fkIvitation_idx` (`invitationTarget` ASC),
  CONSTRAINT `fkIvitationTarget`
    FOREIGN KEY (`invitationTarget`)
    REFERENCES `WarOfViruses`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WarOfViruses`.`Device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WarOfViruses`.`Device` ;

CREATE TABLE IF NOT EXISTS `WarOfViruses`.`Device` (
  `token` VARCHAR(255) NOT NULL,
  `user` BIGINT NOT NULL,
  PRIMARY KEY (`token`),
  INDEX `user_idx` (`user` ASC),
  CONSTRAINT `fkDeviceOwner`
    FOREIGN KEY (`user`)
    REFERENCES `WarOfViruses`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WarOfViruses`.`Contacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WarOfViruses`.`Contacts` ;

CREATE TABLE IF NOT EXISTS `WarOfViruses`.`Contacts` (
  `user` BIGINT NOT NULL,
  `friend` BIGINT NOT NULL,
  PRIMARY KEY (`user`, `friend`),
  INDEX `fkFriends2_idx` (`friend` ASC),
  CONSTRAINT `fkFriends1`
    FOREIGN KEY (`user`)
    REFERENCES `WarOfViruses`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkFriends2`
    FOREIGN KEY (`friend`)
    REFERENCES `WarOfViruses`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WarOfViruses`.`Game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WarOfViruses`.`Game` ;

CREATE TABLE IF NOT EXISTS `WarOfViruses`.`Game` (
  `id` BIGINT NOT NULL,
  `playerCrosses` BIGINT NOT NULL,
  `playerCrossesType` INT UNSIGNED NOT NULL,
  `playerZeroes` BIGINT NOT NULL,
  `playerZeroesType` INT UNSIGNED NOT NULL,
  `status` INT NOT NULL,
  `gameDate` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fkPlayers_idx` (`playerCrosses` ASC),
  INDEX `fkPlayerZeros_idx` (`playerZeroes` ASC),
  CONSTRAINT `fkPlayerCrosses`
    FOREIGN KEY (`playerCrosses`)
    REFERENCES `WarOfViruses`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkPlayerZeros`
    FOREIGN KEY (`playerZeroes`)
    REFERENCES `WarOfViruses`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WarOfViruses`.`Turn`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WarOfViruses`.`Turn` ;

CREATE TABLE IF NOT EXISTS `WarOfViruses`.`Turn` (
  `game` BIGINT NOT NULL,
  `turnNo` INT UNSIGNED NOT NULL,
  `type` INT NOT NULL,
  `x` INT NULL,
  `y` INT NULL,
  PRIMARY KEY (`game`, `turnNo`),
  CONSTRAINT `fkTurns`
    FOREIGN KEY (`game`)
    REFERENCES `WarOfViruses`.`Game` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
